CREATE TABLE users (
  id_user VARCHAR(50) PRIMARY KEY NOT NULL,
  nama VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  role ENUM('ADMIN', 'STAFF') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE kategori (
  id_kategori VARCHAR(50) PRIMARY KEY NOT NULL,
  nama_kategori VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE barang (
  id_barang VARCHAR(50) PRIMARY KEY NOT NULL,
  id_kategori VARCHAR(50) NOT NULL,
  nama_barang VARCHAR(100) NOT NULL,
  stok INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_kategori) REFERENCES kategori(id_kategori)
);

CREATE TABLE peminjaman (
  id_peminjaman VARCHAR(50) PRIMARY KEY NOT NULL,
  id_peminjam VARCHAR(50) NOT NULL,
  id_barang VARCHAR(50) NOT NULL,
  status ENUM('PENDING', 'ACCEPTED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  jumlah INT UNSIGNED NOT NULL DEFAULT 1,
  tanggal_pinjam DATE NOT NULL,
  tanggal_pengembalian DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_peminjam) REFERENCES users(id_user),
  FOREIGN KEY (id_barang) REFERENCES barang(id_barang)
);

CREATE TABLE riwayat (
  id_riwayat VARCHAR(50) PRIMARY KEY NOT NULL,
  id_peminjaman VARCHAR(50) NOT NULL,
  id_peminjam VARCHAR(50) NOT NULL,
  id_approver VARCHAR(50) NOT NULL,
  id_barang VARCHAR(50) NOT NULL,
  status ENUM('PENDING', 'ACCEPTED', 'REJECTED') NOT NULL,
  jumlah INT UNSIGNED NOT NULL,
  tanggal_pinjam DATE NOT NULL,
  tanggal_pengembalian DATE NOT NULL,
  approved_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_peminjaman) REFERENCES peminjaman(id_peminjaman),
  FOREIGN KEY (id_peminjam) REFERENCES users(id_user),
  FOREIGN KEY (id_approver) REFERENCES users(id_user),
  FOREIGN KEY (id_barang) REFERENCES barang(id_barang)
);
